### ISSUE TITLE
Error in CONFIG_URL if OS distribution name contains space

### ISSUE THREAD

**Issue by FlorentF9** [EPFL-ENAC/ENACdrives#29]
An error is thrown if the OS distribution name in CONFIG_URL contains spaces, for example with "Linux Mint".

I fixed it by changing line 235 in `utility.py` to: `os=urllib.parse.quote(OS_DISTRIB + "-" + OS_SYS)`.

**Comment by sbancal** [comment]
Thank you for reporting this.
If I understand correctly, you're not stuck with this bug ? Or are you ?
I'll include this correction in our next release.
